version: '3.8'
services:
 petclinic_compose:
   build:
     context: .
   ports:
     - 8080:8080
   environment:
     - SERVER_PORT=8080
     - MYSQL_URL=jdbc:mysql://mysqlserver_compose/petclinic
   volumes:
     - ./:/app
   depends_on:
     - mysqlserver_compose

 mysqlserver_compose:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data_compose:/var/lib/mysql
      - mysql_config_compose:/etc/mysql/conf.d
volumes:
    mysql_data_compose:
    mysql_config_compose:
